### PR TITLE
use globalThis

### PR DESCRIPTION
**Pull request by ddumont**

### CODE REVIEW

**Comment by feross** [comment]
Why is this an improvement? This package is specifically for getting references to the WebRTC objects in a browser environment.

**Comment by ddumont** [comment]
I believe this was an issue that I encountered when I started trying to embed this lib into a web-worker.   They don't support web-rtc (yet?) so it's kind of moot.  But node/web/workers/etc are moving in the direction of having `globalThis` represent a cross-platform top-level `this`.

If you don't want it, it's not a problem.

**Review by feross — APPROVED** [review]

**Comment by feross** [comment]
Fair enough. I'm happy to preemptively merge this in case workers ever get support. I think this slightly reduces the number of browsers which we'll properly detect WebRTC support in but it's a small number of really old browsers.

**Comment by feross** [comment]
Released as 1.1.0

**Comment by alfredomariamilano** [comment]
This breaks in WebViews on older devices (namely Android and FireOS <= 5), because even if they do support globalThis in the browser, they don't in WebViews. I'll make a pull request to fix this.

**Pull request merged**
